### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by shivam-spyne** [jiaw-z/CoR-GS#23]
`(corgs) **********DS3H:CoR-GS$ bash scripts/run_360.sh 
[500, 2000, 3000, 5000, 7000, 10000, 15000, 30000]
Traceback (most recent call last):
  File "train.py", line 469, in <module>
    safe_state(args.quiet)
  File "./exp/CoR-GS/utils/general_utils.py", line 139, in safe_state
    torch.cuda.set_device(torch.device("cuda:0"))
  File "./.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 399, in set_device
    torch._C._cuda_setDevice(device)
  File "./.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available`

**Comment by shivam-spyne** [comment]
found walkaround , os.environ['CUDA_VISIBLE_DEVICES'] = '0',worked for me
