### ISSUE TITLE
RuntimeError: tabulate: failed to synchronize: cudaErrorInvalidConfiguration: invalid configuration argument

### ISSUE THREAD

**Issue by 2927803072** [jiaw-z/CoR-GS#25]
[500, 2000, 3000, 5000, 7000, 10000, 15000, 30000]
Optimizing output/llff/fern
Output folder: output/llff/fern [08/08 16:52:17]
Tensorboard not available: not logging progress [08/08 16:52:17]
args.source_path  is data/nerf_llff_data/fern [08/08 16:52:17]
############ load llff ############ [08/08 16:52:17]
Reading camera 20/20 [08/08 16:52:17]
2.8834194898605348 cameras_extent [08/08 16:52:17]
Loading Training Cameras 1.0 [08/08 16:52:17]
3it [00:03,  1.24s/it]
Loading Test Cameras 1.0 [08/08 16:52:21]
3it [00:01,  2.77it/s]
Number of points at initialisation :  0 [08/08 16:52:27]
Traceback (most recent call last):
  File "train.py", line 472, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args)
  File "train.py", line 66, in training
    scene = Scene(args, gaussians, shuffle=False)
  File "/home/jy/demo/CoR-GS-main/scene/__init__.py", line 120, in __init__
    self.gaussians.create_from_pcd(scene_info.point_cloud, self.cameras_extent)
  File "/home/jy/demo/CoR-GS-main/scene/gaussian_model.py", line 144, in create_from_pcd
    dist2 = torch.clamp_min(distCUDA2(fused_point_cloud)[0], 0.0000001)
RuntimeError: tabulate: failed to synchronize: cudaErrorInvalidConfiguration: invalid configuration argument

Hello, I have encountered a certain issue for which I am uncertain of the cause. Could you please provide guidance on how to resolve it? Your assistance would be greatly appreciated.

**Comment by 2927803072** [comment]
I use 3090， ubuntu 20..04

**Comment by azzarelli** [comment]
I have the same issue, did you resolve it?
